### ISSUE TITLE
how to use-it?

### ISSUE THREAD

**Issue by sarahBuisson** [EzequielB/jar-to-dep#1]
Hello, I don't understand how your lib work.

By example I want to integrate this lib to my node project : 
https://mvnrepository.com/artifact/io.github.microutils/kotlin-logging-js/1.6.26

How do I do -it?

**Comment by EzequielB** [comment]
Hi, 
I changed the readme to improve the phrasing.
It's a simple tool to find the deps of a set of jars, mostly used for migrating old projects into gradle|maven.
